blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/skarllot/RaiqubToolkit#guide
    about: Read our documentation.
  - name: ⭐ Sponsor Raiqub Toolkit
    url: https://github.com/sponsors/skarllot
    about: Help the continued development.
  - name: 💬 Ask on Github Discussions
    url: https://github.com/skarllot/RaiqubToolkit/discussions
    about: The best place for asking general purpose questions.
